"""Generate luauvmp/signatures.py from a labelled sample."""
import sys, json, io, os
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
from luauvmp.analyse import analyse

LABELS = {
 3:'JUMPIFNOTLE',10:'ORK',11:'MULK',15:'FORNPREP',19:'CLOSEUPVALS',27:'LOADB',
 28:'FORNLOOP',40:'FORGLOOP',45:'JUMPXEQKB',46:'NEWCLOSURE',50:'JUMPIFNOT',
 51:'JUMPIFEQ',54:'JUMPXEQKS',55:'CONCAT',59:'JUMP',61:'GETTABLEN',62:'DIVK',
 72:'SETUPVAL',82:'GETTABLE',87:'GETTABLEKS',90:'JUMPIF',95:'MODK',104:'NAMECALL',
 107:'JUMPIFLE',112:'JUMPXEQKS',113:'GETVARARGS',114:'GETUPVAL',120:'RETURN',
 130:'SUB',134:'SETTABLE',135:'NEWTABLE',137:'LOADK',140:'LOADNIL',142:'LOADNIL',
 148:'NEWCLOSURE2',166:'ADD',171:'MOVE',187:'JUMPIFNOTEQ',193:'NOP',
 196:'JUMPXEQKNIL',197:'DECIMPORT',198:'JUMPIFNOTLT',208:'ADDK',211:'SETTABLEKS',
 218:'NOP',221:'CALL',222:'JUMP',223:'SETLIST',224:'FORGPREP',226:'LOADN',
 232:'FORGPREP_F',236:'LEN',245:'GETIMPORT',248:'SETTABLEN',250:'NOP',
 253:'DECSTR',255:'DECSTR',
}

src = io.open(sys.argv[1], encoding='utf-8', errors='surrogateescape').read()
spec, rep, _ = analyse(src)
sigs, unlabelled = {}, []
for op, (state, sig, fseq, xors) in sorted(rep.handlers.items()):
    name = LABELS.get(op)
    if not name:
        unlabelled.append(op)
        continue
    if sig in sigs and sigs[sig] != name:
        print('CONFLICT', op, name, 'vs', sigs[sig])
    sigs[sig] = name
print('handlers:', len(rep.handlers), 'signatures:', len(sigs))
print('unlabelled opcodes present in sample:', sorted(set(unlabelled))[:40], '...' if len(set(unlabelled))>40 else '')
out = ['"""Handler fingerprints -> canonical Luau opcode names.',
       '',
       'Generated by tools/gen_signatures.py.  A signature is one opcode handler in',
       'canonical form: identifiers, field slots, state numbers and XOR masks erased,',
       'so it stays stable when the protector reshuffles them between builds.',
       '"""', '', 'SIGNATURES = {']
for sig, name in sorted(sigs.items(), key=lambda kv: kv[1]):
    out.append('    %r:\n        %r,' % (sig, name))
out.append('}')
io.open(os.path.join(ROOT, 'luauvmp', 'signatures.py'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('written', len(sigs))
